# API del DENUE

La API del DENUE te permite consultar datos de identificación, ubicación, actividad económica y tamaño de más de 5 millones de establecimientos a nivel nacional, por entidad federativa y municipio. Esta puede utilizarse para crear aplicaciones que muestren la información directamente de las bases de datos del INEGI en el preciso momento en que se actualiza.

Los indicadores que se tienen disponible por establecimiento son los siguientes:
* CLEE
* Id de establecimiento
* Nombre del establecimiento
* Razón social
* Clase de la actividad económica
* Estrato (Personal ocupado)
* Tipo de la vialidad
* Calle
* Número exterior
* Número interior
* Colonia
* Código postal
* Localidad, municipio y entidad federativa
* Teléfono
* Correo electrónico
* Página de internet
* Tipo de establecimiento
* Longitud
* Latitud

Esta API provee de diferentes métodos para obtener información incluyendo:
* **Buscar**. Realiza una consulta de todos los establecimientos que cumplan las condiciones definidas.
* **Ficha**. Obtiene la información de un establecimiento en específico.
* **Nombre**. Realiza una consulta de todos los establecimientos por nombre o razón social y puede ser acotado por entidad federativa.
* **BuscarEntidad**. Realiza una consulta de todos los establecimientos y puede ser acotada por entidad federativa.
* **BuscarAreaAct**. Realiza una consulta de todos los establecimientos con la opción de acotar la búsqueda por área geográfica, actividad económica, nombre y clave del establecimiento.
* **BuscarAreaActEstr**. Realiza una consulta de todos los establecimientos con la opción de acotar la búsqueda por área geográfica, actividad económica, nombre,clave del establecimiento y estrato.
* **Cuantificar**. Realiza un conteo de todos los establecimientos con la opción de acotar la búsqueda por área geográfica, actividad económica y estrato.

La documentación completa puede encontrarse en el siguiente [enlace](https://www.inegi.org.mx/servicios/api_denue.html).

## 1. Token de Autenticación

El Token es un número único que permite hacer consultas. Este permite identificar a los usuarios y la cantidad de consultas realizadas. Para obtenerlo accede a la página de documentación en la pestaña "Guía para desarrolladores". En cada uno de los métodos se tiene el enlace para registrarse en la descripción del parámetro `token`.

![Figure 1](https://miro.medium.com/max/700/1*KEh7ODpDdculfXK2x4w6pw.png)

Una vez que te has registrado, revisa tu correo para identificar tu token.

In [121]:
import requests
import pandas as pd

In [122]:
token = "19ac4341-af8a-46e1-8fc8-f2e9131f0539"

## 2. BuscarEntidad

El método ``BuscarEntidad` permite realizar una consulta de todos los establecimientos de una entidad federativa. De acuerdo a la documentación, sus parámetros son los siguientes:


* **Condición**. Palabra(s) a buscar dentro del nombre del establecimiento, razón social, calle, colonia, clase de la actividad económica, entidad federativa, municipio y localidad. Para buscar todos los establecimientos se deberá ingresar la palabra "todos".
* **Entidad federativa**. Clave de dos dígitos de la entidad federativa (01 a 32). Para incluir todas las entidades se especifica 00.
* **Registro inicial**. Número de registro a partir del cuál se mostrarán los resultados de la búsqueda.
* **Registro final**. Número de registro final que se mostrará en los resultados de la búsqueda.
* **Token**. Número único que permite hacer consultas, el cual se puede obtener al registrarse aquí

De acuerdo a la documentación parar localizar los restaurantes de Chiapas (Entidad 7, [Documentación](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiw3_Kt6qD6AhW1TjABHR-iCbEQFnoECAIQAw&url=https%3A%2F%2Fwww.inegi.org.mx%2Frnm%2Findex.php%2Fcatalog%2F209%2Fdownload%2F6075&usg=AOvVaw2ddXCn_6INr2ZIYFfTZjuA)) del Registro 1 al 100 se emplearía la siguiente URL:

`https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/restaurantes/7/1/100/[Aquí va tu token]`

In [148]:
# URL
url = f"https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/restaurantes/09/1/100/{"19ac4341-af8a-46e1-8fc8-f2e9131f0539"}"
url

'https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/restaurantes/09/1/100/19ac4341-af8a-46e1-8fc8-f2e9131f0539'

In [124]:
# Petición de Datos
response = requests.get(url)
print(f"Código de respuesta: {response.status_code}")

Código de respuesta: 200

In [125]:
# Datos
data_json = response.json()

In [126]:
# DataFrame
data_dataframe =  pd.DataFrame(data_json)

In [127]:
# Encabezado
data_dataframe.head()

,CLEE,Id,Nombre,Razon_social,Clase_actividad,Estrato,Tipo_vialidad,Calle,Num_Exterior,Num_Interior,...,Ubicacion,Telefono,Correo_e,Sitio_internet,Tipo,Longitud,Latitud,tipo_corredor_industrial,nom_corredor_industrial,numero_local
0,10005722513012091000000000U1,8635328,MENUDO SIN NOMBRE,,Restaurantes con servicio de preparación de an...,0 a 5 personas,CALLE,FRANCISCO URBALEJO,227,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.58992243,24.05790603,,,
1,10005722516001801000000000U9,10153290,10 18 SUSHI,,Restaurantes de autoservicio,0 a 5 personas,AVENIDA,REAL DEL MEZQUITAL,115,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.65096843,24.00004258,,,
2,10005722516001444000003286S8,9436321,11201 DURANGO MADERO,OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFI...,Restaurantes de autoservicio,11 a 30 personas,BOULEVARD,DOMINGO ARRIETA,809,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,DOMINOSPIZZA@ALSEA.NET,WWW.DOMINOS.COM.MX,Fijo,-104.66218939,24.00680459,,,
3,10005722516001454000003286S7,9409324,11567 LOMAS DEL PARQUE,OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFI...,Restaurantes de autoservicio,11 a 30 personas,BOULEVARD,LICENCIADO ARMANDO DEL CASTILLO FRANCO,110,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,DOMINOSPIZZA@ALSEA.NET,WWW.DOMINOS.COM.MX,Fijo,-104.69012843,24.01869450,,,
4,10005722516001434000003286S9,9438474,11888 PASEO DURANGO,OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFI...,Restaurantes de autoservicio,11 a 30 personas,BOULEVARD,FELIPE PESCADOR,1401,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,DOMINOSPIZZA@ALSE.NET,WWW.DOMINOS.COM.MX,Fijo,-104.65128776,24.03469947,,,

In [151]:
# Tamaño
data_dataframe.shape
#print(data_dataframe)

(100, 22)

Ahora tratemos de generalizar la petición

In [153]:
condicion        = "todos"  # Si escribimos "todos" nos deolverá todos los tipos de unidades económicas
entidad          = 10      #Chiapas es la Entidad 7
registro_inicial = 1
registro_final   = 100000000

In [154]:
# url
url = f'https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/{condicion}/{entidad}/{registro_inicial}/{registro_final}/{"19ac4341-af8a-46e1-8fc8-f2e9131f0539"}'
url

'https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/todos/10/1/100000000/19ac4341-af8a-46e1-8fc8-f2e9131f0539'

# Petición
response = requests.get(url)

In [183]:
# Datos
data_json = response.json()
# DataFrame
data_dataframe = pd.DataFrame(data_json)

In [182]:
data_dataframe.head()

,CLEE,Id,Nombre,Razon_social,Clase_actividad,Estrato,Tipo_vialidad,Calle,Num_Exterior,Num_Interior,...,Ubicacion,Telefono,Correo_e,Sitio_internet,Tipo,Longitud,Latitud,tipo_corredor_industrial,nom_corredor_industrial,numero_local
0,10005722513012091000000000U1,8635328,MENUDO SIN NOMBRE,,Restaurantes con servicio de preparación de an...,0 a 5 personas,CALLE,FRANCISCO URBALEJO,227,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.58992243,24.05790603,,,
1,10005722516001801000000000U9,10153290,10 18 SUSHI,,Restaurantes de autoservicio,0 a 5 personas,AVENIDA,REAL DEL MEZQUITAL,115,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.65096843,24.00004258,,,
2,10005722516001444000003286S8,9436321,11201 DURANGO MADERO,OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFI...,Restaurantes de autoservicio,11 a 30 personas,BOULEVARD,DOMINGO ARRIETA,809,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,DOMINOSPIZZA@ALSEA.NET,WWW.DOMINOS.COM.MX,Fijo,-104.66218939,24.00680459,,,
3,10005722516001454000003286S7,9409324,11567 LOMAS DEL PARQUE,OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFI...,Restaurantes de autoservicio,11 a 30 personas,BOULEVARD,LICENCIADO ARMANDO DEL CASTILLO FRANCO,110,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,DOMINOSPIZZA@ALSEA.NET,WWW.DOMINOS.COM.MX,Fijo,-104.69012843,24.01869450,,,
4,10005722516001434000003286S9,9438474,11888 PASEO DURANGO,OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFI...,Restaurantes de autoservicio,11 a 30 personas,BOULEVARD,FELIPE PESCADOR,1401,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,DOMINOSPIZZA@ALSE.NET,WWW.DOMINOS.COM.MX,Fijo,-104.65128776,24.03469947,,,

In [184]:
data_dataframe.shape

(100, 22)

1. Crea una función `BuscarEntidad()` en Python, que reciba los parámetros de entrada, consulte la API anteriormente descrita y devuelva un dataframe con los resultados.

In [185]:
def BuscarEntidad(condicion, entidad, registro_inicial, registro_final, token):
    # La ruta correcta lleva /consulta/
    url = f'https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/{condicion}/{entidad}/{registro_inicial}/{registro_final}/{token}'
    
    response = requests.get(url)
    
    # Es vital convertir a JSON y luego a DataFrame dentro de la función
    if response.status_code == 200:
        return pd.DataFrame(response.json())
    else:
        print(f"Error: {response.status_code}")
        return pd.DataFrame()

In [186]:
data_frame = BuscarEntidad('todos', 10, 1, 100, token)
data_frame.head()

,CLEE,Id,Nombre,Razon_social,Clase_actividad,Estrato,Tipo_vialidad,Calle,Num_Exterior,Num_Interior,...,Ubicacion,Telefono,Correo_e,Sitio_internet,Tipo,Longitud,Latitud,tipo_corredor_industrial,nom_corredor_industrial,numero_local
0,10005722513012091000000000U1,8635328,MENUDO SIN NOMBRE,,Restaurantes con servicio de preparación de an...,0 a 5 personas,CALLE,FRANCISCO URBALEJO,227,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.58992243,24.05790603,,,
1,10008327991000031000000000U2,11500181,#1 MARMOLERIA NUEVA,,Fabricación de productos a base de piedras de ...,0 a 5 personas,CALLE,ALBERTO M ALVARADO,0,,...,"GUADALUPE VICTORIA, Guadalupe Victoria, DURANGO",,,,Fijo,-104.12294915,24.44380824,,,
2,10005515120000133000000000U0,6326085,@FM,XHOHFM SA DE CV,Estaciones de transmisión de programas de radio,6 a 10 personas,AVENIDA,CIMA,320,,...,"VICTORIA DE DURANGO, Durango, DURANGO",6183661841,CONTABILIDAD.DURANGO@RPGRADIO.MX,WWW.RADIORAMADURANGO.COM,Fijo,-104.62680423,24.05199816,,,
3,10005463310002091000000000U7,7320254,0 S ZAPATERIA,,Comercio al por menor de calzado,0 a 5 personas,CALLE,PASTEUR,322,0,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.66741869,24.02390492,,,
4,10007463111000073002004471S5,6325998,004 MODATELAS GOMEZ PALACIO,MODATELAS SAPI DE CV,Comercio al por menor de telas,6 a 10 personas,AVENIDA,GUADALUPE VICTORIA,163,,...,"GÓMEZ PALACIO, Gómez Palacio, DURANGO",,TIENDAENLINEA@MODATELAS.COM.MX,WWW.MODATELAS.COM,Fijo,-103.49685260,25.56593946,,,

2. Considerando `data_dataframe`, ¿cuales son las `Clase_actividad` con mayor registros?

In [187]:
conteo_actividades = data_frame['Clase_actividad'].value_counts()
print("Clases de actividad con mayor número de registros:")
print(conteo_actividades.head(5))

Clases de actividad con mayor número de registros:
Clase_actividad
Comercio al por menor de ropa, excepto de bebé y lencería                        12
Comercio al por menor de electrodomésticos menores y aparatos de línea blanca     9
Asociaciones y organizaciones religiosas                                          8
Comercio al por mayor de leche y otros productos lácteos                          5
Restaurantes de autoservicio                                                      4
Name: count, dtype: int64

3. Considerando `data_dataframe`, ¿cuales son los `Estrato` con mayor registros?

In [159]:
conteo_estratos = data_frame['Estrato'].value_counts()
print("Distribución de empresas por Estrato:")
conteo_estratos.to_frame()

Distribución de empresas por Estrato:

                    count
Estrato
0 a 5 personas         40
6 a 10 personas        24
11 a 30 personas       20
51 a 100 personas       7
101 a 250 personas      4
31 a 50 personas        3
251 y más personas      2

4. Lee acerca del método `Buscar` en la documentación. Realiza una consulta de todos los establecimientos que cumplan las condiciones definidas. Crea una función en Python que tenga como parámetros, los elementos necesarios para consultar la API, realice la consulta y devuelva un dataframe con los resultados. Ubica los establecimientos a 100 m del Parque Central de Tuxtla Gutiérrez.

In [181]:

def Buscar(condicion, latitud, longitud, radio, token):
    # La URL correcta para búsqueda por radio geográfico
    url = f"https://www.inegi.org.mx/app/api/denue/v1/identifica/buscar/{condicion}/{latitud}/{longitud}/{radio}/{token}"
    
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return pd.DataFrame(response.json())
        else:
            print(f"Error en la petición: {response.status_code}")
            return pd.DataFrame()
    except Exception as e:
        print(f"Ocurrió un error: {e}")
        return pd.DataFrame()

# Coordenadas Parque Central Tuxtla Gutiérrez
lat = "16.7530"
lon = "-93.1145"
radio_metros = "100"

# Ejecutar consulta
df_parque = Buscar("todos", lat, lon, radio_metros, token)

# Mostrar resultados
print(f"Se encontraron {df_parque.shape[0]} establecimientos.")
df_parque.head()

Error en la petición: 404
Se encontraron 0 establecimientos.

Empty DataFrame
Columns: []
Index: []

5. ¿Cuáles son las `Clase_actividad` con mayor registros en la petición anterior?

In [180]:
conteo_actividades = df_parque['Clase_actividad'].value_counts()
print(conteo_actividades.head())

KeyError: 'Clase_actividad'