# WB4.3 Introducción a SQL

En esta cuaderno de trabajo se explorarán la base de datos `music.db` mediante consultas de SQL. La base de datos contiene tres tablas:
* `songs`, que contiene un identificador `_id`, el título de la canción `title` y el album `album`. 
* `albums`, que contiene un identificador `_id`, el nombre del album `name` y el artista `artist`. 
* `artists`, que contiene un identificador `_id` y su nombre `name`. 

Completa las siguientes instrucciones de acuerdo a lo visto en el tema.

## 1. Acceso a los Datos con Queries.

1. Crea la conexión y un cursor a la base de datos.

In [20]:
import sqlite3
import pandas as pd

In [19]:
connection = sqlite3.connect('music.db')

In [18]:
curr = connection.cursor()

2. Explora todas las columnas en todas antes mencionadas tablas. Muestra los primeros 10 registros.

In [4]:
query_albums = "SELECT * FROM albums LIMIT 10;"
df_albums = pd.read_sql_query(query_albums, connection)
df_albums

   _id                              name  artist
0    1                Tales of the Crown      16
1    2               The Masquerade Ball      16
2    3                             Grace     159
3    4               Behind Closed Doors     147
4    5                         Day & Age     121
5    6                 Sweet Fanny Adams     172
6    7                     Spem In Alium     199
7    8                 Night In The Ruts     152
8    9                          Impurity      95
9   10  Concerto For Group and Orchestra     196

In [5]:
query_songs = "SELECT * FROM songs LIMIT 10;"
df_songs = pd.read_sql_query(query_songs, connection)
df_songs

   _id  track                                title  album
0    1      2                I Can't Quit You Baby    343
1    2      1        Taking the Easy Way Out Again    311
2    3      6                   Let's Have A Party    260
3    4      7                    Flaming Telepaths    104
4    5     11                             Yearnin'     37
5    6      1                      Bat Out Of Hell    290
6    7      5                           Evil Woman    143
7    8      7                            Rat Salad     50
8    9      8                     Young is a World    402
9   10      3  Sam With The Showing Scalp Flat Top    429

In [6]:
query_artists = "SELECT * FROM artists LIMIT 10;"
df_artists = pd.read_sql_query(query_artists, connection),
df_artists

(   _id                               name
 0    1                      Mahogany Rush
 1    2                                Elf
 2    3                          Mehitabel
 3    4  Big Brother & The Holding Company
 4    5                         Roy Harper
 5    6                        Pat Benatar
 6    7                     Rory Gallagher
 7    8                        Iron Maiden
 8    9                      Blaster Bates
 9   10                       Procol Harum,)

3. Iron Maiden tiene como `_id = 8`en la tabla de artistas. Emplea este id para identificar sus álbumes en la tabla `albums`. Observa que la columna `artist` hace referencia a los id de los artistas.

In [16]:
query_maiden = "SELECT * FROM albums WHERE artist = 8;"
df_maiden = pd.read_sql_query(query_maiden, connection)
df_maiden

   _id                          name  artist
0  236       The Number of the Beast       8
1  412                    Powerslave       8
2  420  Seventh Son Of A Seventh Son       8

4. Muestras las canciones del album "The Number of the Beast". Presenta tus resultados en orden alfabético.

In [66]:
query_songs_beast = """
SELECT track, title, album 
FROM songs 
WHERE album = 236 
ORDER BY title ASC;
"""

df_beast = pd.read_sql_query(query_songs_beast, connection)
df_beast

   track                                            title  album
0      4         22 Acacia Avenue (1998 Digital Remaster)    236
1      2   Children Of The Damned (1998 Digital Remaster)    236
2      7                 Gangland (1998 Digital Remaster)    236
3      9     Hallowed Be Thy Name (1998 Digital Remaster)    236
4      1                 Invaders (1998 Digital Remaster)    236
5      6         Run To The Hills (1998 Digital Remaster)    236
6      5  The Number Of The Beast (1998 Digital Remaster)    236
7      3             The Prisoner (1998 Digital Remaster)    236
8      8            Total Eclipse (1998 Digital Remaster)    236

## 2. Agregaciones y Agrupamientos de Datos.

1. ¿Cuantas canciones, albumes y artistas se tienen registrados en la base de datos?

In [40]:
conteo_general = {
    "Total Canciones": pd.read_sql_query("SELECT COUNT(*) FROM songs;", connection).iloc[0,0],
    "Total Álbumes": pd.read_sql_query("SELECT COUNT(*) FROM albums;", connection).iloc[0,0],
    "Total Artistas": pd.read_sql_query("SELECT COUNT(*) FROM artists;", connection).iloc[0,0]
}

In [41]:
df_resumen = pd.DataFrame(list(conteo_general.items()), columns=['Categoría', 'Cantidad'])
df_resumen

         Categoría  Cantidad
0  Total Canciones      5350
1    Total Álbumes       439
2   Total Artistas       201

2. Agrupa la tabla albums por artista para identificar qué cuales son los 5 artistas que tienen más albumes.

In [43]:
query_top_artists = """
SELECT artists.name, COUNT(albums._id) AS total_albums
FROM artists
JOIN albums ON artists._id = albums.artist
GROUP BY artists.name
ORDER BY total_albums DESC
LIMIT 5;
"""

df_top_artists = pd.read_sql_query(query_top_artists, connection)
df_top_artists

             name  total_albums
0   Black Sabbath            18
1  Axel Rudi Pell            15
2    Led Zeppelin            14
3     Deep Purple            13
4       Aerosmith            13

3. Presenta el nombre de los artistas identificados en el punto anterior.

In [44]:
df_nombres_artistas = df_top_artists[['name']]
df_nombres_artistas

             name
0   Black Sabbath
1  Axel Rudi Pell
2    Led Zeppelin
3     Deep Purple
4       Aerosmith

4. ¿Cuál es el album con más canciones? Investiga sobre este album en la red.

In [58]:
query_max_songs = """
SELECT albums.name, COUNT(songs._id) AS numero_de_canciones
FROM songs
JOIN albums ON songs.album = albums._id
GROUP BY albums.name
ORDER BY numero_de_canciones DESC
LIMIT 1;
"""

In [59]:
df_album_ganador = pd.read_sql_query(query_max_songs, connection)
df_album_ganador

        name  numero_de_canciones
0  Cornology                   72

## 3. Combinación de Tablas.

1. Muestra todas el nombre canciones del album "Seventh Son Of A Seventh Son" que tiene por '_id = 420'. Presenta la lista en el *track order* (`track`).

In [61]:
query_seventh_son = """
SELECT songs.track, songs.title
FROM songs
JOIN albums ON songs.album = albums._id
WHERE albums._id = 420
ORDER BY songs.track ASC;
"""
df_seventh_son = pd.read_sql_query(query_seventh_son, connection)
df_seventh_son

   track                                              title
0      1                  Moonchild (1998 Digital Remaster)
1      2            Infinite Dreams (1998 Digital Remaster)
2      3    Can I Play With Madness (1998 Digital Remaster)
3      4       The Evil That Men Do (1998 Digital Remaster)
4      5  Seventh Son Of A Seventh Son (1998 Digital Rem...
5      6               The Prophecy (1998 Digital Remaster)
6      7            The Clairvoyant (1998 Digital Remaster)
7      8    Only The Good Die Young (1998 Digital Remaster)

2. Obtén todas las canciones de Aeroesmith en orden alfabético. Solo incluye el título en la salida ¿Cuántas son?

In [62]:
query_aerosmith = """
SELECT songs.title
FROM songs
JOIN albums ON songs.album = albums._id
JOIN artists ON albums.artist = artists._id
WHERE artists.name = 'Aerosmith'
ORDER BY songs.title ASC;
"""

In [64]:
df_aerosmith = pd.read_sql_query(query_aerosmith, connection)

#conteo total
total_canciones = len(df_aerosmith)
print("Aeroesmith")
print(f"Total de canciones: {total_canciones}")
df_aerosmith

Aeroesmith
Total de canciones: 151

                                title
0     (Dulcimer Stomp) The Other Side
1    (Going Down) Love In An Elevator
2        (Hoodoo) Voodoo Medicine Man
3      (Water Song) Janie's Got A Gun
4                        Adam's Apple
..                                ...
146                     What It Takes
147                Woman Of The World
148                          Write Me
149                 You See Me Crying
150                        Young Lust

[151 rows x 1 columns]

## Referencias
* Actividad basada en SQLite-Exercises: https://github.com/IancuIulian/SQLite-Exercises